### ISSUE TITLE
Test failure on s390x

### ISSUE THREAD

**Issue by nmeum** [rizsotto/Bear#309]
While packaging Bear for Alpine Linux I ran into the following test failure on our builder for the s390x architecture:

```
Test project /builds/nmeum/aports/testing/bear/src/Bear-3.0.0/build/subprojects/Build/BearSource
    Start 1: bear::citnames_unit_test
1/9 Test #1: bear::citnames_unit_test .........   Passed    0.01 sec
    Start 2: bear::result_unit_test
2/9 Test #2: bear::result_unit_test ...........   Passed    0.00 sec
    Start 3: bear::flags_unit_test
3/9 Test #3: bear::flags_unit_test ............   Passed    0.00 sec
    Start 4: bear::report_unit_test
4/9 Test #4: bear::report_unit_test ...........   Passed    0.00 sec
    Start 5: bear::shell_unit_test
5/9 Test #5: bear::shell_unit_test ............   Passed    0.02 sec
    Start 6: bear::sys_unit_test
6/9 Test #6: bear::sys_unit_test ..............   Passed    0.00 sec
    Start 7: bear::intercept_unit_test
7/9 Test #7: bear::intercept_unit_test ........   Passed    0.01 sec
    Start 8: bear::er_unit_test
8/9 Test #8: bear::er_unit_test ...............   Passed    0.01 sec
    Start 9: bear::exec_unit_test
9/9 Test #9: bear::exec_unit_test .............***Exception: SegFault  0.00 sec
```

The entire build log can be found here:  [alpine-linux-s390x-bear.txt](https://github.com/rizsotto/Bear/files/5347831/alpine-linux-s390x-bear.txt)

Not sure if you can debug / fix this form the log file. I don't have access to the s390x architecture myself.

See #308 for more information.

**Comment by rizsotto** [comment]
Could you re-run against latest master?

- the build log is not very detailed enough to see what's the problem. Maybe a backtrace from the core file?
- I've managed to run the full test set on x86_64.

**Comment by rizsotto** [comment]
Closing it, because I believe it's fixed now. Recent release (3.0.1) contains fixes for this.

Will re-open if needed.

**Comment by nmeum** [comment]
Unfortunately, 3.0.1 still fails with the same error. As I said, I have absolutely no way of debugging this myself because I don't have access to s390x. So not sure if this is worth reopening.

[alpine-edge-s390x-bear.txt](https://github.com/rizsotto/Bear/files/5496159/alpine-edge-s390x-bear.txt)

**Comment by musicinmybrain** [comment]
I ran into this while updating grpc in Fedora Linux: https://bugzilla.redhat.com/show_bug.cgi?id=1959600.

I am not the maintainer of the bear package in Fedora, but I can do as many “scratch builds” on s390x as necessary, with any patches or adjustments to help with debugging. I don‘t have shell access for interactive debugging, although it‘s my understanding I may be able to get it if needed.

Let me know if you want me to try anything.

**Comment by rizsotto** [comment]
Thanks @musicinmybrain for your message.

I am curious about this failure. :) Could you update the version to try to build the latest `3.0.11`? (I would rather fix the HEAD than branch from `3.0.7`.) Also, could you tell if the tool set (compiler, linker, dependencies) on this platform are the same (match with versions) as on `x86_64`?

**Comment by musicinmybrain** [comment]
Here‘s a scratch build for the latest version: https://koji.fedoraproject.org/koji/taskinfo?taskID=67776896

All architectures show the same versions here (in `root.log`):

```
DEBUG util.py:446:  Installing:
DEBUG util.py:446:   cmake                     x86_64   3.20.2-1.fc35                 build   6.5 M
DEBUG util.py:446:   fmt-devel                 x86_64   7.1.3-3.fc35                  build   108 k
DEBUG util.py:446:   gcc                       x86_64   11.1.1-1.fc35                 build    32 M
DEBUG util.py:446:   gcc-c++                   x86_64   11.1.1-1.fc35                 build    12 M
DEBUG util.py:446:   gmock-devel               x86_64   1.10.0-6.fc35                 build   145 k
DEBUG util.py:446:   grpc-devel                x86_64   1.26.0-15.fc35                build   182 k
DEBUG util.py:446:   grpc-plugins              x86_64   1.26.0-15.fc35                build   214 k
DEBUG util.py:446:   gtest-devel               x86_64   1.10.0-6.fc35                 build   170 k
DEBUG util.py:446:   json-devel                x86_64   3.9.1-4.fc35                  build   153 k
DEBUG util.py:446:   make                      x86_64   1:4.3-5.fc35                  build   539 k
DEBUG util.py:446:   python3                   x86_64   3.9.5-1.fc35                  build    28 k
DEBUG util.py:446:   spdlog-devel              x86_64   1.8.5-1.fc35                  build    70 k
```

as well as in the other packages I could see. The `s390x` chroot does install a few extra packages, including `libubsan`, `libasan`, and `libatomic`. The `binutils`/`binutils-gold` version is 2.36.1-9.fc35.

From https://kojipkgs.fedoraproject.org//work/tasks/6910/67776910/build.log:

```
[ 77%] Performing test step for 'BearSource'
cd /builddir/build/BUILD/Bear-3.0.11/s390x-redhat-linux-gnu/subprojects/Build/BearSource && ctest
Test project /builddir/build/BUILD/Bear-3.0.11/s390x-redhat-linux-gnu/subprojects/Build/BearSource
    Start 1: bear::result_unit_test
1/7 Test #1: bear::result_unit_test ...........   Passed    0.00 sec
    Start 2: bear::flags_unit_test
2/7 Test #2: bear::flags_unit_test ............   Passed    0.00 sec
    Start 3: bear::shell_unit_test
3/7 Test #3: bear::shell_unit_test ............   Passed    0.02 sec
    Start 4: bear::sys_unit_test
4/7 Test #4: bear::sys_unit_test ..............   Passed    0.00 sec
    Start 5: bear::exec_unit_test
5/7 Test #5: bear::exec_unit_test .............***Exception: SegFault  1.05 sec
    Start 6: bear::intercept_unit_test
6/7 Test #6: bear::intercept_unit_test ........   Passed    0.01 sec
    Start 7: bear::citnames_unit_test
7/7 Test #7: bear::citnames_unit_test .........   Passed    0.02 sec
86% tests passed, 1 tests failed out of 7
Total Test time (real) =   1.11 sec
The following tests FAILED:
	  5 - bear::exec_unit_test (SEGFAULT)
Errors while running CTest
Output from these tests are in: /builddir/build/BUILD/Bear-3.0.11/s390x-redhat-linux-gnu/subprojects/Build/BearSource/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
```

I‘ll see if I can get more detailed output, but if you have suggestions on the best way to do this, it will save some time.

(The `grpc` package itself does have some unexplained test failures on s390x, so it‘s possible the problem is actually there. We’ll see once we hopefully get a backtrace.)

**Comment by musicinmybrain** [comment]
Just to show the failure still occurs with current grpc, here is a scratch build using the grpc 1.37.1 update not yet merged into the Fedora repositories: https://koji.fedoraproject.org/koji/taskinfo?taskID=67777988

**Comment by rizsotto** [comment]
Thanks @musicinmybrain 

```shell
$ ldd ../Bear.build/subprojects/Build/BearSource/intercept/exec_unit_test
	linux-vdso.so.1 (0x00007ffea6160000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f5b01a98000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f5b01a91000)
	libgtest_main.so.1.10.0 => /lib64/libgtest_main.so.1.10.0 (0x00007f5b01a8c000)
	libgmock.so.1.10.0 => /lib64/libgmock.so.1.10.0 (0x00007f5b01a6d000)
	libgtest.so.1.10.0 => /lib64/libgtest.so.1.10.0 (0x00007f5b01a08000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f5b01820000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f5b016d8000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f5b016bd000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f5b014f2000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f5b01ad6000)
```

In theory, the failed unit test has no dependencies on the gRPC package. I've seen similar crashes with Clang cfi sanitizer (with more unit test failures), which caused by the gmock library. Will create a patch version which does not use it.

**Comment by musicinmybrain** [comment]
This should help:

```
+ valgrind --track-origins=yes s390x-redhat-linux-gnu/subprojects/Build/BearSource/intercept/exec_unit_test
==2068747== Memcheck, a memory error detector
==2068747== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==2068747== Using Valgrind-3.17.0 and LibVEX; rerun with -h for copyright info
==2068747== Command: s390x-redhat-linux-gnu/subprojects/Build/BearSource/intercept/exec_unit_test
==2068747== 
Running main() from /builddir/build/BUILD/googletest-release-1.10.0/googletest/src/gtest_main.cc
[==========] Running 34 tests from 7 test suites.
[----------] Global test environment set-up.
[----------] 4 tests from Session
[ RUN      ] Session.dont_crash_on_nullptr
[       OK ] Session.dont_crash_on_nullptr (10 ms)
[ RUN      ] Session.capture_on_empty
[       OK ] Session.capture_on_empty (6 ms)
[ RUN      ] Session.capture_silent
[       OK ] Session.capture_silent (3 ms)
[ RUN      ] Session.capture_verbose
[       OK ] Session.capture_verbose (2 ms)
[----------] 4 tests from Session (32 ms total)
[----------] 4 tests from PathIterator
[ RUN      ] PathIterator.works_on_empty
[       OK ] PathIterator.works_on_empty (1 ms)
[ RUN      ] PathIterator.works_on_single
[       OK ] PathIterator.works_on_single (2 ms)
[ RUN      ] PathIterator.works_on_multiple
[       OK ] PathIterator.works_on_multiple (9 ms)
[ RUN      ] PathIterator.works_with_empty_values
[       OK ] PathIterator.works_with_empty_values (2 ms)
[----------] 4 tests from PathIterator (16 ms total)
[----------] 9 tests from Executor
[ RUN      ] Executor.fails_without_session
libexec.so: Executor.cc; session is not initialized
libexec.so: Executor.cc; session is not initialized
libexec.so: Executor.cc; session is not initialized
libexec.so: Executor.cc; session is not initialized
libexec.so: Executor.cc; session is not initialized
[       OK ] Executor.fails_without_session (130 ms)
[ RUN      ] Executor.execve_silent_library
[       OK ] Executor.execve_silent_library (56 ms)
[ RUN      ] Executor.execve_verbose_library
[       OK ] Executor.execve_verbose_library (14 ms)
[ RUN      ] Executor.execvpe_fails_on_resolve
[       OK ] Executor.execvpe_fails_on_resolve (16 ms)
[ RUN      ] Executor.execvpe_passes
[       OK ] Executor.execvpe_passes (27 ms)
[ RUN      ] Executor.execvp2_passes
[       OK ] Executor.execvp2_passes (27 ms)
[ RUN      ] Executor.spawn_passes
==2068747== Invalid read of size 8
==2068747==    at 0x137662: UnknownInlinedFun (Executor.cc:91)
==2068747==    by 0x137662: el::Executor::posix_spawn(int*, char const*, posix_spawn_file_actions_t const*, posix_spawnattr_t const*, char* const*, char* const*) const [clone .constprop.0] (Executor.cc:172)
==2068747==    by 0x120DB9: (anonymous namespace)::Executor_spawn_passes_Test::TestBody() [clone .lto_priv.0] (ExecutorTest.cc:265)
==2068747==    by 0x48DD6D9: ??? (in /usr/lib64/libgtest.so.1.10.0)
==2068747==    by 0x48C2D89: testing::Test::Run() (in /usr/lib64/libgtest.so.1.10.0)
==2068747==    by 0x48C2F55: testing::TestInfo::Run() (in /usr/lib64/libgtest.so.1.10.0)
==2068747==    by 0x48C31B5: testing::TestSuite::Run() (in /usr/lib64/libgtest.so.1.10.0)
==2068747==    by 0x48CC4FD: testing::internal::UnitTestImpl::RunAllTests() (in /usr/lib64/libgtest.so.1.10.0)
==2068747==    by 0x48CB1D1: testing::UnitTest::Run() (in /usr/lib64/libgtest.so.1.10.0)
==2068747==    by 0x4875893: main (in /usr/lib64/libgtest_main.so.1.10.0)
==2068747==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
==2068747== 
==2068747== 
==2068747== Process terminating with default action of signal 11 (SIGSEGV): dumping core
==2068747==  Access not within mapped region at address 0x0
==2068747==    at 0x137662: UnknownInlinedFun (Executor.cc:91)
==2068747==    by 0x137662: el::Executor::posix_spawn(int*, char const*, posix_spawn_file_actions_t const*, posix_spawnattr_t const*, char* const*, char* const*) const [clone .constprop.0] (Executor.cc:172)
==2068747==    by 0x120DB9: (anonymous namespace)::Executor_spawn_passes_Test::TestBody() [clone .lto_priv.0] (ExecutorTest.cc:265)
==2068747==    by 0x48DD6D9: ??? (in /usr/lib64/libgtest.so.1.10.0)
==2068747==    by 0x48C2D89: testing::Test::Run() (in /usr/lib64/libgtest.so.1.10.0)
==2068747==    by 0x48C2F55: testing::TestInfo::Run() (in /usr/lib64/libgtest.so.1.10.0)
==2068747==    by 0x48C31B5: testing::TestSuite::Run() (in /usr/lib64/libgtest.so.1.10.0)
==2068747==    by 0x48CC4FD: testing::internal::UnitTestImpl::RunAllTests() (in /usr/lib64/libgtest.so.1.10.0)
==2068747==    by 0x48CB1D1: testing::UnitTest::Run() (in /usr/lib64/libgtest.so.1.10.0)
==2068747==    by 0x4875893: main (in /usr/lib64/libgtest_main.so.1.10.0)
==2068747==  If you believe this happened as a result of a stack
==2068747==  overflow in your program's main thread (unlikely but
==2068747==  possible), you can try to increase the size of the
==2068747==  main thread stack using the --main-stacksize= flag.
==2068747==  The main thread stack size used in this run was 8388608.
==2068747== 
==2068747== HEAP SUMMARY:
==2068747==     in use at exit: 18,752 bytes in 209 blocks
==2068747==   total heap usage: 1,220 allocs, 1,011 frees, 225,668 bytes allocated
==2068747== 
==2068747== LEAK SUMMARY:
==2068747==    definitely lost: 0 bytes in 0 blocks
==2068747==    indirectly lost: 0 bytes in 0 blocks
==2068747==      possibly lost: 0 bytes in 0 blocks
==2068747==    still reachable: 18,752 bytes in 209 blocks
==2068747==         suppressed: 0 bytes in 0 blocks
==2068747== Rerun with --leak-check=full to see details of leaked memory
==2068747== 
==2068747== For lists of detected and suppressed errors, rerun with: -s
==2068747== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
```

**Comment by musicinmybrain** [comment]
So as I read it, the question is just how `CommandBuilder()` is getting passed a null session reference.

**Comment by musicinmybrain** [comment]
It looks like the problem goes away when I disable link-time optimization (LTO).

That still implies there is probably a correctness problem somewhere, but it is a usable workaround.

**Comment by rizsotto** [comment]
That could be it!!!

My command line was this to reproduce the error: `-flto -fvisibility=hidden -fsanitize=cfi` And I was suspicious about the sanitizer, but the LTO is more likely.
